apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-12-10T01:34:38Z"
  generation: 1
  labels:
    name: test-bigip-controller-1
  name: test-bigip-controller-1
  namespace: kube-system
  resourceVersion: "5329908"
  uid: b7cedcaa-4460-4ec8-8706-741b6c5e8018
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test-bigip-controller-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-bigip-controller-1
    spec:
      containers:
      - args:
        - --bigip-partition
        - test
        - --bigip-url
        - 10.145.69.216
        - --bigip-username
        - admin
        - --bigip-password
        - admin
        - --verify-interval
        - "2"
        - --node-poll-interval
        - "1"
        - --log-level
        - DEBUG
        - --as3-validation=true
        - --disable-teems=true
        - --insecure
        - --log-as3-response=true
        - --custom-resource-mode=true
        - --ipam=true
        - --flannel-name
        - /test/vxlan-tunnel-mp
        - --pool-member-type
        - cluster
        command:
        - /app/bin/k8s-bigip-ctlr
        image: nandakishoref5/k8s-bigip-ctlr:ts_statusok_final_v13
        imagePullPolicy: IfNotPresent
        name: test-bigip-controller-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: bigip-controller
      serviceAccountName: bigip-controller
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-12-10T01:34:39Z"
    lastUpdateTime: "2021-12-10T01:34:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-12-10T01:34:38Z"
    lastUpdateTime: "2021-12-10T01:34:39Z"
    message: ReplicaSet "test-bigip-controller-1-55c8cb5469" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
