apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2021-12-10T01:33:22Z"
  name: bigip-controllers
  resourceVersion: "5329756"
  uid: 1ece2762-6db9-47b1-bf04-f373c55bdd7e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bigip-controller-role
subjects:
- kind: ServiceAccount
  name: bigip-controller
  namespace: kube-system
