apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: "2021-12-10T01:34:41Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: fic-volume-claim
    namespace: kube-system
    resourceVersion: "5329938"
    uid: 7a41d3f6-55cd-4bf9-8a55-5788778bc5ea
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: local-storage
    volumeMode: Filesystem
    volumeName: fic-volume
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
