apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: "2021-12-10T01:34:41Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: fic-volume
    resourceVersion: "5329936"
    uid: d632e309-00cc-4cbf-b5d6-3cd908a5de8b
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: fic-volume-claim
      namespace: kube-system
      resourceVersion: "5329916"
      uid: 7a41d3f6-55cd-4bf9-8a55-5788778bc5ea
    local:
      path: /tmp/localstorage
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - unique-foxhound-worker0.pdsea.f5net.com
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-storage
    volumeMode: Filesystem
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
